# Generated by Django 3.0.3 on 2020-02-19 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0002_auto_20200219_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='subcshool',
            new_name='subschool',
        ),
    ]
