# Generated by Django 3.0.3 on 2020-02-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0003_auto_20200219_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='spell_resist',
            new_name='spell_resistence',
        ),
    ]
