# Generated by Django 3.0.3 on 2020-02-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0004_auto_20200219_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='description_formatted',
            new_name='description_formated',
        ),
    ]
