# Generated by Django 3.0.3 on 2020-02-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0005_auto_20200219_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spell',
            name='costly_components',
            field=models.CharField(max_length=255, verbose_name='Costly components'),
        ),
    ]
