# Generated by Django 3.0.3 on 2020-02-19 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spell', '0006_auto_20200219_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spell',
            old_name='bloodranger',
            new_name='bloodrager',
        ),
    ]
